version: "3.8"

services:
  react:
    build: ./react
    volumes:
      - ./react/app:/usr/src/app
    ports:
      - "3000:3000"
    expose:
      - "3000"

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8000:8000"
    expose: 
      - "8000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./react/app/build:/var/www
    working_dir: /workspace
